#!/usr/bin/env python3
from cclib.io import ccread
import sys
import os

def convert(filename):
    basename, ext = os.path.splitext(filename)
    ext = ext.lower()

    if ext in [".fchk"]:
        data = ccread(filename)

        coords = data.atomcoords[-1]
        numbers = data.atomnos

        freqs = data.vibfreqs
        modes = data.vibdisps

        output_file = f"{basename}.xyz"

        with open(output_file, "w") as f:

            for mode_id, (freq, mode) in enumerate(zip(freqs, modes)):

                f.write(f"{len(numbers)}\n")
                f.write(f"frequency at {freq:.2f} 1/cm\n")

                for Z, (x, y, z), (dx, dy, dz) in zip(numbers, coords, mode):
                    f.write(
                        f"{Z:2d}  "
                        f"{x:12.6f} {y:12.6f} {z:12.6f}  "
                        f"{dx:10.6f} {dy:10.6f} {dz:10.6f}\n"
                    )

        print(f"Converted {filename} → {output_file}")

    else:
        print("Unsupported format. Only .fchk supported.")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: fchktoxyz <input_file>")
        sys.exit(1)

    filename = sys.argv[1]
    convert(filename)
